### ISSUE TITLE
Uptade to 18.3b3

### ISSUE THREAD

**Issue by Extarys** [Sirillion/SMXmenuPatch#1]
I'd love to use this hub in the 18.3 build. I get 20 more fps using this version - so I crank up the video settings :D

**Comment by Sirillion** [comment]
The changes done to 18.3 made a patching method not all that viable due to the amount of changes the font change introduced. I spent that time updating the modlets themselves instead to make them ready for 18.3 stable.

**Comment by Extarys** [comment]
I understand. I'm trying to create a mod to make another mod compatible with SMX and now I see how much trouble all of this must be.

Thanks for your hard work.
